name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '14'
          - '16'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install system dependencies
        run: |
          sudo apt-get update && \
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential \
            nodejs \
            python \
            pkg-config \
            libx11-6 \
            libx11-dev \
            libxi6 \
            libxi-dev \
            libglx-mesa0 \
            libglx-dev \
            libglew-dev \
            libegl1-mesa-dev
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies and build package
        run: npm install
        # This will also cause our "install" script to run, building the gl package
