name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build (Node ${{ matrix.node }} on ${{ matrix.runner }}-${{ matrix.arch }})
    strategy:
      matrix:
        runner:
          - ubuntu-20.04
          - macos-11
        node:
          - '14'
          - '16'
        arch:
          - 'x64'
          - 'arm64'

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install system dependencies
        run: scripts/install-dependencies.sh
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build package
        run: npm run rebuild -- --arch=${{ matrix.arch }}
