name: Release

on:
  push:
    tags: ['v*']

jobs:
  publish_binaries:
    name: Publish Binaries (${{ matrix.runner }})
    strategy:
      matrix:
        runner:
          - ubuntu-20.04
          - macos-11
        node:
          - '14'
          - '16'
        arch:
          - 'x64'
          - 'arm64'
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install system dependencies
        run: scripts/install-dependencies.sh
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install package
        run: npm install
        # This will also cause our "install" script to run, building the gl package
      - name: Build binaries
        run: |
          npx node-pre-gyp configure
          npx node-pre-gyp build --target_arch=${{ matrix.arch }}
          npx node-pre-gyp package
      - uses: actions/upload-artifact@v2
        with:
          name: binary ${{matrix.node}} ${{matrix.runner}} ${{matrix.arch}}
          path: build/stage/
  publish_npm:
    name: Publish to NPM
    needs:
      - publish_binaries
    runs-on: ubuntu-20.04
    steps:
      # Download all binaries
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install system dependencies
        run: scripts/install-dependencies.sh
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm
      - name: Install package
        run: npm install
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      - name: Publish binaries to github release
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx node-pre-gyp-github publish --release
      - name: Publish package
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc && \
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
